### ISSUE TITLE
Timeouts to low

### ISSUE THREAD

**Issue by Teifun2** [Leptopoda/nextcloud_cookbook_dart_api#1]
https://github.com/Leptopoda/nextcloud_cookbook_dart_api/blob/5465b2fd64fb71cb7cd588989d1709fd48884457/lib/src/api.dart#L33

I Think these Timeouts are way to short.

I understand that in an ideal world the response should never take longer than 3 seconds.

But if connectivity is slow or server was hibernating or anything else is true, the user should still be able to receive the recipes even after 20 seconds if he is willing to wait so long. 

In my opinion timeout is used to indicate that very obviously something has gone completely bad. We can no longer expect server to respond. I would set this to 30 seconds or maybe even 60 seconds.

**Comment by Leptopoda** [comment]
Although I don't agree that 30 seconds should be used we can up the limit.
The change should be done in
 https://github.com/Teifun2/nextcloud-cookbook-flutter/blob/de0535dcb0409c9e79bd25796715c021cd3d4223/lib/src/services/api_provider.dart#L10-L12

As this repo is all generated code and the next generation would overwrite it.
Just create a new dio instance with the basepath and some custom (or even none if desired) and pass it to the lib.

**Comment by Teifun2** [comment]
What would be an acceptable timeout in your opinion?

**Comment by Leptopoda** [comment]
I haven't used dio much but judging from the parameter names we have a connection timeout and a recive timeout.

I must admit that my setup is fairly responsive so I don't really know :(
Once a connection is established the server should be fast enough to return data in 3 to 10 seconds. I'd guess that the connection time is limiting most of the time.

It's still your app we're talking about so if you feel fine with no timeout at all just remove it. It shouldn't bother the other users so there is no reason to keep it.

**Comment by Teifun2** [comment]
The thing that i am worried about is that nextcloud is run by a lot of people in "homelab" situation. Sometimes maybe even raspis or similar. They often accept slow latency because they know they can host themselfes & have a hobby project. To set the timeout low has in my opinion no real benefit. We are no high risk application where you need to know asap that something is broken if response does not come fast.

So my opinion is, if something is really broken then a user has to wait 30 seconds to see a timeout. But in slow environments this should suffice to not "cut" to early while the server might still repsond.
